print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun")
print("Yay! Printing.")
print("I'd much rather that you 'not'.")
print('I "said" do not touch this.')
print("Hi i am the creatortor")